pipeline {
    agent any

    tools {
        maven 'Maven3'
    }

    stages {
        stage('Checkout') {
            steps { checkout scm }
        }

        stage('Build') {
            steps { bat 'mvn -B clean package' }
        }

        stage('Run') {
            steps { bat 'mvn -q exec:java -Dexec.mainClass="com.comp367.App"' }
        }
    }

    post {
        success { echo 'Build and Run successful!' }
        failure { echo 'Build failed!' }
    }
}